"""secure_partner_schema

Revision ID: 918432a86228
Revises: 9f651605664a
Create Date: 2026-09-04 04:38:46.757325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918432a86228'
down_revision: Union[str, Sequence[str], None] = '9f651605664a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('signing_secret', sa.String(), nullable=False),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_earnings', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_workers', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partners_api_key_hash'), ['api_key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_partners_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_partners_id'), ['id'], unique=False)

    op.create_table('partner_api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('partner_id', sa.String(), nullable=False),
    sa.Column('key_value', sa.String(), nullable=False),
    sa.Column('secret_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('rotated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_value')
    )
    with op.batch_alter_table('partner_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_api_keys_partner_id'), ['partner_id'], unique=False)

    op.create_table('earnings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('is_missing_data', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('earnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_earnings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_earnings_worker_id'), ['worker_id'], unique=False)

    op.create_table('partner_commissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('partner_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_commissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_commissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_commissions_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_commissions_worker_id'), ['worker_id'], unique=False)

    op.create_table('partner_workers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('partner_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_workers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_workers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_workers_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_workers_worker_id'), ['worker_id'], unique=False)

    op.create_table('sdk_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('partner_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('sdk_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sdk_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sdk_tokens_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sdk_tokens_worker_id'), ['worker_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('transaction_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_worker_id'), ['worker_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_worker_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('sdk_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sdk_tokens_worker_id'))
        batch_op.drop_index(batch_op.f('ix_sdk_tokens_partner_id'))
        batch_op.drop_index(batch_op.f('ix_sdk_tokens_id'))

    op.drop_table('sdk_tokens')
    with op.batch_alter_table('partner_workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_workers_worker_id'))
        batch_op.drop_index(batch_op.f('ix_partner_workers_partner_id'))
        batch_op.drop_index(batch_op.f('ix_partner_workers_id'))

    op.drop_table('partner_workers')
    with op.batch_alter_table('partner_commissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_commissions_worker_id'))
        batch_op.drop_index(batch_op.f('ix_partner_commissions_partner_id'))
        batch_op.drop_index(batch_op.f('ix_partner_commissions_id'))

    op.drop_table('partner_commissions')
    with op.batch_alter_table('earnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_earnings_worker_id'))
        batch_op.drop_index(batch_op.f('ix_earnings_id'))

    op.drop_table('earnings')
    with op.batch_alter_table('partner_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_api_keys_partner_id'))
        batch_op.drop_index(batch_op.f('ix_partner_api_keys_id'))

    op.drop_table('partner_api_keys')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_id'))
        batch_op.drop_index(batch_op.f('ix_partners_email'))
        batch_op.drop_index(batch_op.f('ix_partners_api_key_hash'))

    op.drop_table('partners')
    # ### end Alembic commands ###
