"""Add Member 4 Protection Engine

Revision ID: 9f651605664a
Revises: 687c62b13f6f
Create Date: 2026-09-04 01:49:30.521229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f651605664a'
down_revision: Union[str, Sequence[str], None] = '687c62b13f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_pots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'),
    sa.Column('total_contributed', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'),
    sa.Column('total_used', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'),
    sa.Column('period_contributed', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'),
    sa.Column('period_start', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id')
    )
    op.create_index(op.f('ix_emergency_pots_id'), 'emergency_pots', ['id'], unique=False)
    op.create_table('credit_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('stability_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_assessments_id'), 'credit_assessments', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_credit_assessments_id'), table_name='credit_assessments')
    op.drop_table('credit_assessments')
    op.drop_index(op.f('ix_emergency_pots_id'), table_name='emergency_pots')
    op.drop_table('emergency_pots')
    # ### end Alembic commands ###
