"""Update partner system tables

Revision ID: c1427943b491
Revises: 918432a86228
Create Date: 2026-09-04 05:41:04.545962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1427943b491'
down_revision: Union[str, Sequence[str], None] = '918432a86228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_commissions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('commission_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=255), nullable=False, server_default='temp_key'))
        batch_op.alter_column('webhook_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('commission_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_earnings',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_partners_api_key_hash'))
        batch_op.create_index(batch_op.f('ix_partners_api_key'), ['api_key'], unique=True)
        batch_op.drop_column('api_key_hash')
        batch_op.drop_column('signing_secret')

    with op.batch_alter_table('sdk_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=512), nullable=False, server_default='temp_token'))
        batch_op.alter_column('token_hash',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.create_unique_constraint('uq_sdk_tokens_token', ['token'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sdk_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sdk_tokens_token', type_='unique')
        batch_op.alter_column('token_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.drop_column('token')

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signing_secret', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('api_key_hash', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_partners_api_key'))
        batch_op.create_index(batch_op.f('ix_partners_api_key_hash'), ['api_key_hash'], unique=1)
        batch_op.alter_column('total_earnings',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
        batch_op.alter_column('commission_rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('webhook_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('api_key')

    with op.batch_alter_table('partner_commissions', schema=None) as batch_op:
        batch_op.alter_column('commission_rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
